[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
extra_output = ["storageLayout"]
ast = true
ffi = true
build_info = true

[rpc_endpoints]
base = "https://mainnet.base.org"
baseSepolia = "https://sepolia.base.org"

[etherscan]
baseSepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
